Repository AY2223S1-CS2103-F14-1/tp, pull requests merged in 2022-11, with the labels that each got.

#154 Fix PickCommand bug
  src/main/java/nus/climods/logic/commands/PickCommand.java
  src/main/java/nus/climods/logic/parser/PickCommandParser.java
  src/main/java/nus/climods/model/module/Module.java
  src/test/java/nus/climods/logic/commands/PickCommandTest.java
  src/test/java/nus/climods/logic/parser/AddCommandParserTest.java
  src/test/java/nus/climods/logic/parser/PickCommandParserTest.java
Labels: type.Bug, priority.Medium

#163 Remove `AB3` legacy files and general clean up
  build.gradle
  src/main/java/nus/climods/MainApp.java
  src/main/java/nus/climods/commons/core/LogsCenter.java
  src/main/java/nus/climods/commons/core/Messages.java
  src/main/java/nus/climods/logic/Logic.java
  src/main/java/nus/climods/logic/LogicManager.java
  src/main/java/nus/climods/logic/parser/parameters/RelaxedParser.java
  src/main/java/nus/climods/model/AddressBook.java
  src/main/java/nus/climods/model/ReadOnlyAddressBook.java
  src/main/java/nus/climods/model/ReadOnlyUserPrefs.java
  src/main/java/nus/climods/model/UserPrefs.java
  src/main/java/nus/climods/model/module/Tutorial.java
  src/main/java/nus/climods/model/module/UniqueUserModuleList.java
  src/main/java/nus/climods/model/person/Address.java
  src/main/java/nus/climods/model/person/Email.java
  src/main/java/nus/climods/model/person/Name.java
  src/main/java/nus/climods/model/person/NameContainsKeywordsPredicate.java
  src/main/java/nus/climods/model/person/Person.java
  src/main/java/nus/climods/model/person/Phone.java
  src/main/java/nus/climods/model/person/UniquePersonList.java
  src/main/java/nus/climods/model/person/exceptions/DuplicatePersonException.java
  src/main/java/nus/climods/model/person/exceptions/PersonNotFoundException.java
  src/main/java/nus/climods/model/tag/Tag.java
  src/main/java/nus/climods/model/util/SampleDataUtil.java
  src/main/java/nus/climods/storage/AddressBookStorage.java
  src/main/java/nus/climods/storage/JsonAdaptedPerson.java
  src/main/java/nus/climods/storage/JsonAdaptedTag.java
  src/main/java/nus/climods/storage/JsonAddressBookStorage.java
  src/main/java/nus/climods/storage/JsonSerializableAddressBook.java
  src/main/java/nus/climods/storage/JsonUserPrefsStorage.java
  src/main/java/nus/climods/storage/Storage.java
  src/main/java/nus/climods/storage/StorageManager.java
  src/main/java/nus/climods/storage/UserPrefsStorage.java
  src/main/java/nus/climods/storage/module/user/UserModuleListStorage.java
  src/main/java/nus/climods/ui/MainWindow.java
  src/main/java/nus/climods/ui/common/StatusBarFooter.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
  src/main/java/nus/climods/ui/module/SavedModuleCard.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
  src/test/data/JsonAddressBookStorageTest/notJsonFormatAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/nus/climods/logic/parser/parameters/CliParserTest.java
  src/test/java/nus/climods/model/module/predicate/ModuleContainsKeywordsPredicateTest.java
Labels: type.Chore

#164 Fix `CommandHistory` bugs
  src/main/java/nus/climods/commons/core/CommandSession.java
  src/test/java/nus/climods/commons/core/CommandSessionTest.java
Labels: type.Bug, severity.High

#160 Fix UI
  src/main/java/nus/climods/ui/MainWindow.java
  src/main/java/nus/climods/ui/common/CommandBox.java
  src/main/java/nus/climods/ui/common/ResultDisplay.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
  src/main/java/nus/climods/ui/module/ModuleListPanel.java
  src/main/java/nus/climods/ui/module/SavedModuleListPanel.java
  src/main/java/nus/climods/ui/module/components/LessonPill.java
  src/main/java/nus/climods/ui/module/components/ModuleCreditsPill.java
  src/main/java/nus/climods/ui/module/components/SemesterPill.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/OneDarkTheme.css
Labels: priority.Medium, UI/UX

#167 Fix issues with `preq`, module code, UG
  docs/UserGuide.md
  src/main/java/nus/climods/logic/commands/AddCommand.java
  src/main/java/nus/climods/logic/commands/PrereqsCommand.java
  src/main/java/nus/climods/logic/commands/ViewCommand.java
  src/main/java/nus/climods/logic/parser/parameters/ModuleCodeParameter.java
  src/test/java/nus/climods/logic/commands/PrereqsCommandTest.java
Labels: type.Bug, severity.High

#168 Update Hong Jin PPP
  docs/team/sarrrdin.md
Labels: documentation

#170 Update Huzaifa's PPP
  docs/team/huzaifa1712.md
Labels: documentation

#165 Update PPP
  docs/team/seeksaveserve.md
  docs/team/shenyih0ng.md
  docs/team/zupey.md
Labels: documentation

#162 Display wrong / missing lesson details bug
  src/main/java/nus/climods/logic/commands/AddCommand.java
  src/main/java/nus/climods/logic/commands/PickCommand.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/model/module/UniqueUserModuleList.java
  src/main/java/nus/climods/model/module/UserModule.java
Labels: type.Bug, severity.High

#172 Fix `pickcommand` bug that cannot pick valid lesson
  src/main/java/nus/climods/logic/parser/ParserUtil.java
  src/main/java/nus/climods/model/module/LessonTypeEnum.java
  src/test/java/nus/climods/logic/parser/PickCommandParserTest.java
Labels: type.Bug

#169 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/Glossary.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/UiClassDiagram.png
  docs/team/johndoe.md
  src/test/java/nus/climods/logic/commands/ListCommandTest.java
Labels: documentation

#178 Finish Hong Jin PPP
  docs/team/sarrrdin.md
Labels: documentation

#176 Finish Huzaifa's PPP
  docs/team/huzaifa1712.md
Labels: documentation

#181 Minor documentation updates
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/commands/PickCommand.png
  docs/team/shenyih0ng.md
Labels: documentation

#182 Update `UI.png`
  docs/images/UI.png
  docs/images/Ui.png
Labels: documentation

#183 Handle nusmods `ApiException` and invalid academic year
  docs/UserGuide.md
  src/main/java/nus/climods/MainApp.java
  src/main/java/nus/climods/model/module/ModuleList.java
  src/main/java/nus/climods/model/module/ReadOnlyModuleList.java
  src/main/java/nus/climods/ui/UiManager.java
  src/test/java/nus/climods/logic/commands/AddCommandTest.java
  src/test/java/nus/climods/logic/commands/ExitCommandTest.java
  src/test/java/nus/climods/logic/commands/FindCommandTest.java
  src/test/java/nus/climods/logic/commands/HelpCommandTest.java
  src/test/java/nus/climods/logic/commands/ListCommandTest.java
  src/test/java/nus/climods/logic/commands/PickCommandTest.java
  src/test/java/nus/climods/logic/commands/PrereqsCommandTest.java
  src/test/java/nus/climods/logic/commands/UserModuleStub.java
  src/test/java/nus/climods/testutil/ModuleListTestUtil.java
Labels: type.Bug, priority.High
