Repository AY2223S1-CS2103-F14-1/tp, pull requests merged in 2022-09, with the labels that each got.

#3 Setup project repository
  README.md
Labels: type.Chore

#13 Add Yi Hong's details
  docs/AboutUs.md
  docs/images/shenyih0ng.png
  docs/team/shenyih0ng.md
Labels: documentation

#18 Update Linus' Details
  docs/AboutUs.md
  docs/images/zupey.png
  docs/team/Linus.md
Labels: documentation

#23 Update `AboutUs.md` with Huzaifa's information
  docs/AboutUs.md
  docs/images/huzaifa1712.png
  docs/team/huzaifa1712.md
Labels: documentation

#24 Add UI mockup and update docs
  README.md
  docs/_config.yml
  docs/_sass/minima/_base.scss
  docs/images/Ui.png
  docs/index.md
Labels: documentation

#28 Update draft user guide
  docs/UserGuide.md
Labels: documentation

#30 Fix `UserGuide.md` formatting errors
  docs/UserGuide.md
Labels: type.Bug, severity.VeryLow

#31 Update Developer Guide
  docs/DeveloperGuide.md
Labels: documentation
