Repository AY2223S1-CS2103-F14-1/tp, pull requests merged in 2022-10, with the labels that each got.

#33 :fire: Add PPP for Cheng Yi
  docs/AboutUs.md
  docs/team/seeksaveserve.md
Labels: documentation

#44 Zupey/update about us
  docs/AboutUs.md
  docs/team/zupey.md
Labels: documentation

#45 `nusmods` API interface
  build.gradle
  src/main/java/org/openapitools/client/ApiClient.java
  src/main/java/org/openapitools/client/ApiException.java
  src/main/java/org/openapitools/client/ApiResponse.java
  src/main/java/org/openapitools/client/Configuration.java
  src/main/java/org/openapitools/client/JSON.java
  src/main/java/org/openapitools/client/Pair.java
  src/main/java/org/openapitools/client/RFC3339DateFormat.java
  src/main/java/org/openapitools/client/ServerConfiguration.java
  src/main/java/org/openapitools/client/ServerVariable.java
  src/main/java/org/openapitools/client/api/ModulesApi.java
  src/main/java/org/openapitools/client/api/VenuesApi.java
  src/main/java/org/openapitools/client/api/openapi.yaml
  src/main/java/org/openapitools/client/model/AbstractOpenApiSchema.java
  src/main/java/org/openapitools/client/model/Lesson.java
  src/main/java/org/openapitools/client/model/LessonWeeks.java
  src/main/java/org/openapitools/client/model/Module.java
  src/main/java/org/openapitools/client/model/ModuleCondensed.java
  src/main/java/org/openapitools/client/model/ModuleInformation.java
  src/main/java/org/openapitools/client/model/ModuleInformationSemesterDataInner.java
  src/main/java/org/openapitools/client/model/PrereqTree.java
  src/main/java/org/openapitools/client/model/PrereqTreeOneOf.java
  src/main/java/org/openapitools/client/model/PrereqTreeOneOf1.java
  src/main/java/org/openapitools/client/model/SemesterData.java
  src/main/java/org/openapitools/client/model/VenueInformation.java
  src/main/java/org/openapitools/client/model/VenueLesson.java
  src/main/java/org/openapitools/client/model/VenueLessonAllOf.java
  src/main/java/org/openapitools/client/model/WeekRange.java
  src/main/java/org/openapitools/client/model/Workload.java
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/test/java/org/openapitools/client/api/ModulesApiTest.java
Labels: priority.High, Infrastructure

#50 Update UI 💅
  .gitignore
  src/main/java/seedu/address/ui/module/Launcher.java
  src/main/java/seedu/address/ui/module/LogicManager.java
  src/main/java/seedu/address/ui/module/MainWindow.java
  src/main/java/seedu/address/ui/module/Module.java
  src/main/java/seedu/address/ui/module/ModuleCard.java
  src/main/java/seedu/address/ui/module/ModuleListPanel.java
  src/main/java/seedu/address/ui/module/SavedModuleCard.java
  src/main/java/seedu/address/ui/module/SavedModuleListPanel.java
  src/main/java/seedu/address/ui/module/Ui.java
  src/main/java/seedu/address/ui/module/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/OneDarkTheme.css
  src/main/resources/view/SavedModuleListCard.fxml
Labels: priority.High, UI/UX, Infrastructure

#51 UI for primary module list and saved modules
  .gitignore
  src/main/java/seedu/address/ui/module/Launcher.java
  src/main/java/seedu/address/ui/module/LogicManager.java
  src/main/java/seedu/address/ui/module/MainWindow.java
  src/main/java/seedu/address/ui/module/Module.java
  src/main/java/seedu/address/ui/module/ModuleCard.java
  src/main/java/seedu/address/ui/module/ModuleListPanel.java
  src/main/java/seedu/address/ui/module/SavedModuleCard.java
  src/main/java/seedu/address/ui/module/SavedModuleListPanel.java
  src/main/java/seedu/address/ui/module/Ui.java
  src/main/java/seedu/address/ui/module/UiManager.java
  src/main/resources/images/address_book_32.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/ModuleListPanel.fxml
  src/main/resources/view/OneDarkTheme.css
  src/main/resources/view/SavedModuleListCard.fxml
Labels: priority.High, UI/UX

#54 Fine tune UI
  src/main/java/nus/climods/ui/common/Pill.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
  src/main/java/nus/climods/ui/module/SavedModuleCard.java
  src/main/java/nus/climods/ui/module/SavedModuleListPanel.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/SavedModuleListCard.fxml
  src/main/resources/view/SavedModuleListPanel.fxml
Labels: priority.Medium, UI/UX

#53 Linus/set up storage infrastructure
  src/main/java/nus/climods/model/module/ModuleSummaryList.java
  src/main/java/nus/climods/model/module/ReadOnlyModuleSummaryList.java
  src/main/java/nus/climods/storage/JsonAdaptedTag.java
  src/main/java/nus/climods/storage/module/JsonModuleSummaryListStorage.java
  src/main/java/nus/climods/storage/module/JsonSerializableModuleSummaryList.java
  src/main/java/nus/climods/storage/module/ModuleSummaryListStorage.java
  src/main/java/nus/climods/storage/module/user/JsonAdaptedModule.java
  src/main/java/nus/climods/storage/module/user/JsonSerializableUserModuleList.java
  src/main/java/nus/climods/storage/module/user/JsonUserModuleListStorage.java
  src/main/java/nus/climods/storage/module/user/UserModuleListStorage.java
  src/test/data/JsonModuleSummaryListStorageTest/notJsonFormatModuleSummaryList.json
  src/test/data/JsonModuleSummaryListStorageTest/validJsonFormatModuleSummaryList.json
  src/test/java/nus/climods/storage/module/JsonModuleSummaryListStorageTest.java
Labels: Infrastructure

#55 [Infrastructure] Parser
  build.gradle
  src/main/java/nus/climods/logic/parser/ParserUtil.java
  src/main/java/nus/climods/logic/parser/parameters/ModuleCodeParameter.java
  src/main/java/nus/climods/logic/parser/parameters/PositionalParameter.java
  src/main/java/nus/climods/logic/parser/parameters/RelaxedParser.java
  src/test/java/nus/climods/logic/parser/parameters/CliParserTest.java
  src/test/java/nus/climods/logic/parser/parameters/ModuleCodeParameterTest.java
  src/test/java/org/openapitools/client/api/VenuesApiTest.java
Labels: Infrastructure

#60 Add support for `find` command
  src/main/java/nus/climods/commons/core/Messages.java
  src/main/java/nus/climods/logic/Logic.java
  src/main/java/nus/climods/logic/LogicManager.java
  src/main/java/nus/climods/logic/commands/FindCommand.java
  src/main/java/nus/climods/logic/parser/AddressBookParser.java
  src/main/java/nus/climods/logic/parser/CliModsParser.java
  src/main/java/nus/climods/logic/parser/FindCommandParser.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/model/module/predicate/ModuleContainsKeywordsPredicate.java
  src/main/java/nus/climods/ui/MainWindow.java
  src/test/java/nus/climods/logic/commands/FindCommandTest.java
  src/test/java/nus/climods/logic/parser/CommandParserTestUtil.java
  src/test/java/nus/climods/logic/parser/FindCommandParserTest.java
  src/test/java/nus/climods/model/module/ModuleStub.java
  src/test/java/nus/climods/model/module/predicate/ModuleContainsKeywordsPredicateTest.java
Labels: type.Story, priority.High

#61 [WIP] Add Ls Command
  src/main/java/nus/climods/commons/core/Messages.java
  src/main/java/nus/climods/logic/Logic.java
  src/main/java/nus/climods/logic/commands/ListCommand.java
  src/main/java/nus/climods/logic/parser/CliModsParser.java
  src/main/java/nus/climods/logic/parser/CliSyntax.java
  src/main/java/nus/climods/logic/parser/ParserUtil.java
  src/main/java/nus/climods/logic/parser/parameters/FacultyCodeParameter.java
  src/main/java/nus/climods/logic/parser/parameters/ModuleCodeParameter.java
  src/main/java/nus/climods/logic/parser/parameters/OptionalPositionalParameter.java
  src/main/java/nus/climods/logic/parser/parameters/UserFlagParameter.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/module/CodeContainsKeywordsPredicate.java
  src/main/java/nus/climods/ui/module/ModuleListPanel.java
  src/main/java/org/openapitools/client/api/ModulesApi.java
  src/main/java/org/openapitools/client/model/Module.java
  src/main/resources/view/SavedModuleListPanel.fxml
  src/test/java/org/openapitools/client/api/ModulesApiTest.java
Labels: type.Story, priority.High

#66 Add Help Command
  build.gradle
  src/main/java/nus/climods/commons/core/Messages.java
  src/main/java/nus/climods/logic/commands/HelpCommand.java
  src/main/java/nus/climods/logic/parser/CliModsParser.java
  src/main/java/nus/climods/logic/parser/HelpCommandParser.java
  src/main/java/nus/climods/ui/MainWindow.java
  src/main/java/nus/climods/ui/common/HelpWindow.java
  src/main/resources/html/UserManual.html
  src/main/resources/view/HelpWindow.fxml
  src/test/java/nus/climods/logic/commands/HelpCommandTest.java
  src/test/java/nus/climods/logic/parser/HelpCommandParserTest.java
Labels: type.Story, priority.Medium

#65 Exit command
  src/main/java/nus/climods/logic/commands/ExitCommand.java
  src/main/java/nus/climods/logic/parser/CliModsParser.java
  src/main/java/nus/climods/logic/parser/ExitCommandParser.java
  src/main/java/nus/climods/ui/MainWindow.java
  src/test/java/nus/climods/logic/commands/ExitCommandTest.java
  src/test/java/nus/climods/logic/parser/ExitCommandParserTest.java
Labels: type.Story, priority.Medium

#59 Add and Delete Module Command
  src/main/java/nus/climods/Main.java
  src/main/java/nus/climods/MainApp.java
  src/main/java/nus/climods/logic/Logic.java
  src/main/java/nus/climods/logic/LogicManager.java
  src/main/java/nus/climods/logic/commands/AddCommand.java
  src/main/java/nus/climods/logic/commands/DeleteCommand.java
  src/main/java/nus/climods/logic/parser/AddCommandParser.java
  src/main/java/nus/climods/logic/parser/CliModsParser.java
  src/main/java/nus/climods/logic/parser/CliSyntax.java
  src/main/java/nus/climods/logic/parser/DeleteCommandParser.java
  src/main/java/nus/climods/logic/parser/ParserUtil.java
  src/main/java/nus/climods/logic/parser/parameters/ModuleCodeParameter.java
  src/main/java/nus/climods/model/AddressBook.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/ReadOnlyAddressBook.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/model/module/ModuleCode.java
  src/main/java/nus/climods/model/module/ModuleList.java
  src/main/java/nus/climods/model/module/ReadOnlyModuleList.java
  src/main/java/nus/climods/model/module/Tutorial.java
  src/main/java/nus/climods/model/module/UniqueUserModuleList.java
  src/main/java/nus/climods/model/module/UserModule.java
  src/main/java/nus/climods/model/module/exceptions/DuplicateUserModuleException.java
  src/main/java/nus/climods/model/module/exceptions/UserModuleNotFoundException.java
  src/main/java/nus/climods/storage/module/JsonSerializableModuleList.java
  src/main/java/nus/climods/ui/MainWindow.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
  src/main/java/nus/climods/ui/module/ModuleListPanel.java
  src/main/java/nus/climods/ui/module/SavedModuleCard.java
  src/main/java/nus/climods/ui/module/SavedModuleListPanel.java
  src/main/java/org/openapitools/client/model/PrereqTree.java
  src/main/resources/view/SavedModuleListCard.fxml
  src/test/java/nus/climods/logic/commands/AddCommandTest.java
  src/test/java/nus/climods/logic/commands/DeleteCommandTest.java
  src/test/java/nus/climods/logic/commands/ExitCommandTest.java
  src/test/java/nus/climods/logic/commands/FindCommandTest.java
  src/test/java/nus/climods/logic/commands/HelpCommandTest.java
  src/test/java/nus/climods/logic/commands/ModelStub.java
  src/test/java/nus/climods/logic/commands/UserModuleStub.java
  src/test/java/nus/climods/logic/parser/AddCommandParserTest.java
  src/test/java/nus/climods/logic/parser/DeleteCommandParserTest.java
Labels: type.Story, priority.High

#76 Linus/fix html redirection bug
  src/main/java/nus/climods/ui/UiManager.java
  src/main/java/nus/climods/ui/common/HelpWindow.java
Labels: type.Bug, priority.Medium

#77 Add mapping between Special Term I/II to Semester 3/4
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
Labels: priority.Low

#80 Better sort order for `find` results
  src/main/java/nus/climods/logic/LogicManager.java
  src/main/java/nus/climods/logic/commands/DeleteCommand.java
  src/main/java/nus/climods/logic/commands/FindCommand.java
  src/main/java/nus/climods/logic/commands/ListCommand.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/module/comparator/ModuleBestMatchKeywordComparator.java
  src/main/java/nus/climods/model/module/predicate/CodeContainsKeywordsPredicate.java
  src/test/java/nus/climods/logic/commands/FindCommandTest.java
  src/test/java/nus/climods/logic/commands/ModelStub.java
Labels: priority.Medium, UI/UX

#81 Add support for command history
  docs/UserGuide.md
  src/main/java/nus/climods/commons/core/CommandSession.java
  src/main/java/nus/climods/logic/Logic.java
  src/main/java/nus/climods/ui/MainWindow.java
  src/main/java/nus/climods/ui/common/CommandBox.java
  src/test/java/nus/climods/commons/core/CommandSessionTest.java
Labels: priority.Medium, UI/UX

#88 Update Developer Guide to add description of `help` command
  docs/DeveloperGuide.md
Labels: documentation

#87 Update DG for AddCommand
  docs/DeveloperGuide.md
Labels: documentation, priority.High

#89 Update DG with additional details for parameter classes
  docs/DeveloperGuide.md
Labels: documentation

#82 Implement storage for UserModuleList and support storage of add and delete
  src/main/java/nus/climods/MainApp.java
  src/main/java/nus/climods/commons/core/CommandSession.java
  src/main/java/nus/climods/logic/Logic.java
  src/main/java/nus/climods/logic/LogicManager.java
  src/main/java/nus/climods/logic/commands/AddCommand.java
  src/main/java/nus/climods/logic/commands/Command.java
  src/main/java/nus/climods/logic/commands/CommandResult.java
  src/main/java/nus/climods/logic/commands/DeleteCommand.java
  src/main/java/nus/climods/logic/commands/ExitCommand.java
  src/main/java/nus/climods/logic/commands/FindCommand.java
  src/main/java/nus/climods/logic/commands/ListCommand.java
  src/main/java/nus/climods/logic/commands/exceptions/CommandException.java
  src/main/java/nus/climods/logic/parser/AddCommandParser.java
  src/main/java/nus/climods/model/AddressBook.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/UserPrefs.java
  src/main/java/nus/climods/model/module/ModuleList.java
  src/main/java/nus/climods/model/module/ReadOnlyModuleList.java
  src/main/java/nus/climods/model/module/UniqueUserModuleList.java
  src/main/java/nus/climods/model/module/UserModule.java
  src/main/java/nus/climods/storage/Storage.java
  src/main/java/nus/climods/storage/StorageManager.java
  src/main/java/nus/climods/storage/exceptions/StorageException.java
  src/main/java/nus/climods/storage/module/user/JsonAdaptedUserModule.java
  src/main/java/nus/climods/storage/module/user/JsonSerializableUserModuleList.java
  src/main/java/nus/climods/storage/module/user/JsonUserModuleListStorage.java
  src/main/java/nus/climods/storage/module/user/UserModuleListStorage.java
  src/main/java/nus/climods/ui/MainWindow.java
  src/main/java/nus/climods/ui/common/CommandBox.java
  src/test/data/JsonUserModuleListStorageTest/notJsonFormatModuleSummaryList.json
  src/test/data/JsonUserModuleListStorageTest/validJsonFormatModuleSummaryList.json
  src/test/data/JsonUserModuleListStorageTest/validJsonFormatUserModuleList.json
  src/test/java/nus/climods/commons/core/CommandSessionTest.java
  src/test/java/nus/climods/logic/commands/ExitCommandTest.java
  src/test/java/nus/climods/logic/commands/FindCommandTest.java
  src/test/java/nus/climods/logic/commands/ModelStub.java
  src/test/java/nus/climods/storage/module/JsonUserModuleListStorageTest.java
Labels: type.Story, priority.High, Infrastructure

#85 Allow users to add Semester data when adding Module
  docs/UserGuide.md
  src/main/java/nus/climods/logic/commands/AddCommand.java
  src/main/java/nus/climods/logic/commands/DeleteCommand.java
  src/main/java/nus/climods/logic/parser/AddCommandParser.java
  src/main/java/nus/climods/logic/parser/ParserUtil.java
  src/main/java/nus/climods/logic/parser/parameters/SemesterTypeParameter.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/model/module/UniqueUserModuleList.java
  src/main/java/nus/climods/model/module/UserModule.java
  src/main/java/nus/climods/storage/module/user/JsonAdaptedUserModule.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
  src/main/java/nus/climods/ui/module/SavedModuleCard.java
  src/main/java/nus/climods/ui/module/components/ModuleCreditsPill.java
  src/main/java/nus/climods/ui/module/components/SemesterPill.java
  src/main/java/org/openapitools/client/model/ModuleCondensed.java
  src/main/java/org/openapitools/client/model/SemestersEnum.java
  src/test/data/JsonUserModuleListStorageTest/validJsonFormatUserModuleList.json
  src/test/java/nus/climods/logic/commands/AddCommandTest.java
  src/test/java/nus/climods/logic/commands/ModelStub.java
  src/test/java/nus/climods/storage/module/JsonUserModuleListStorageTest.java
Labels: type.Story, priority.High

#99 Add Module `Lesson` methods
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/module/LessonType.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/model/module/Semester.java
  src/test/java/nus/climods/model/module/ModuleTest.java
Labels: priority.High, Infrastructure

#101 Add prereqs command (preq)
  src/main/java/nus/climods/logic/commands/PrereqsCommand.java
  src/main/java/nus/climods/logic/parser/CliModsParser.java
  src/main/java/nus/climods/logic/parser/PrereqsCommandParser.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/module/predicate/ModulesByCodesPredicate.java
  src/test/java/nus/climods/logic/commands/PrereqsCommandTest.java
Labels: priority.Medium

#100 Add UI for view lesson
  src/main/java/nus/climods/MainApp.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
  src/main/java/nus/climods/ui/module/components/LessonPill.java
  src/main/resources/view/ModuleListCard.fxml
  src/main/resources/view/OneDarkTheme.css
Labels: priority.High, UI/UX

#84 Pick command
  docs/UserGuide.md
  src/main/java/nus/climods/logic/commands/AddCommand.java
  src/main/java/nus/climods/logic/commands/CommandResult.java
  src/main/java/nus/climods/logic/commands/DeleteCommand.java
  src/main/java/nus/climods/logic/commands/FindCommand.java
  src/main/java/nus/climods/logic/commands/ListCommand.java
  src/main/java/nus/climods/logic/commands/PickCommand.java
  src/main/java/nus/climods/logic/commands/ViewCommand.java
  src/main/java/nus/climods/logic/parser/CliModsParser.java
  src/main/java/nus/climods/logic/parser/ParserUtil.java
  src/main/java/nus/climods/logic/parser/PickCommandParser.java
  src/main/java/nus/climods/logic/parser/parameters/FacultyCodeParameter.java
  src/main/java/nus/climods/logic/parser/parameters/LessonTypeParameter.java
  src/main/java/nus/climods/logic/parser/parameters/ModuleCodeParameter.java
  src/main/java/nus/climods/model/Model.java
  src/main/java/nus/climods/model/ModelManager.java
  src/main/java/nus/climods/model/module/LessonType.java
  src/main/java/nus/climods/model/module/LessonTypeEnum.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/model/module/UniqueUserModuleList.java
  src/main/java/nus/climods/model/module/UserModule.java
  src/main/java/nus/climods/storage/module/user/JsonAdaptedUserModule.java
  src/main/java/nus/climods/ui/module/ModuleCard.java
  src/main/java/nus/climods/ui/module/SavedModuleCard.java
  src/main/resources/view/SavedModuleListCard.fxml
  src/test/data/JsonUserModuleListStorageTest/validJsonFormatUserModuleList.json
  src/test/java/nus/climods/logic/commands/AddCommandTest.java
  src/test/java/nus/climods/logic/commands/PickCommandTest.java
  src/test/java/nus/climods/model/module/ModuleTest.java
  src/test/java/nus/climods/storage/module/JsonUserModuleListStorageTest.java
Labels: type.Story, priority.High

#104 Add unselectable lessons automatically in `add` command
  src/main/java/nus/climods/logic/commands/AddCommand.java
  src/main/java/nus/climods/logic/commands/PickCommand.java
  src/main/java/nus/climods/model/module/Module.java
  src/main/java/nus/climods/model/module/UserModule.java
  src/test/java/nus/climods/logic/commands/AddCommandTest.java
Labels: type.Story, priority.Medium

#102 Update user guide for `v1.3` release
  docs/UserGuide.md
  docs/images/Ui.png
Labels: documentation, priority.High

#158 Fix AboutUs
  docs/AboutUs.md
Labels: documentation
